### ISSUE TITLE
Modify saved response during replay

### ISSUE THREAD

**Issue by siderakis** [ijpiantanida/talkback#10]
My app sets a non-deterministic request id which the response has to match so I need to update the tape to include the request id.

Can we add a new option that allows the outbound tape response to be edited `bodyUpdater`.

```
const opts = {
  host: "http://localhost:9001",
  port: 9000,
  bodyMatcher: (tape, req) => {  /** stripe out request id */},
  bodyUpdater: (tape, req) => { /** get new request id from req and replace old request id instances from the tape */}
}
```

**Comment by ijpiantanida** [comment]
@siderakis I just release v1.6.0 which includes a `responseDecorator` option which is very similar to your `bodyUpdater` proposal.

Thank for the suggestion.
