### ISSUE TITLE
New feature: Ignore parts of the url

### ISSUE THREAD

**Issue by xjohannes** [ijpiantanida/talkback#14]
### The problem:
We have urls that are created from previous server responses like: 
`http://localhost:8081/payments/${paymentId}/transactions/${transactionId}/import`
where `http://localhost:8080` is the host key in the options object and `/${paymentId}/transactions/${transactionId}/import is the url key in the recorded tapes.`

As far as I understand, Talkback uses the url key when matching tapes. This will force a new call to the real server for every new variable value.

### A solution:
A solution is to introduce a url/[pathname](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/pathname) matcher property, where one could replace the variables with fixed values. I guess its much the same solution as you did with the bodyMatcher.

**Comment by ijpiantanida** [comment]
I just released v1.7.0 which adds the `urlMatcher` option.
As you suggested, it works in the same way as the `bodyMatcher` option.

You can see it under use in the `example` folder.

Thanks for the suggestion.
