### ISSUE TITLE
Name of the talkback server in the summary

### ISSUE THREAD

**Issue by roypa** [ijpiantanida/talkback#15]
When running our tests we are starting 10 talkback servers, one for each of the different services our app is accessing. When the test runner terminates, all talkback servers reports their individual exit summary.

It would have been nice to distinguish the different exit summaries.
What if a talkback server can be given a `name` in its options, which them can be printed in the SUMMARY heading if present?

Example:
```
===== SUMMARY Customer server =====
Unused tapes:
- GET_customers_by_customerNumber.json5
- PUT_change_telephoneNumber_for_newly_made_customer.json5
===== SUMMARY Messaging server =====
===== SUMMARY Sales server =====
===== SUMMARY Order server =====
Unused tapes:
- UseCase-1_13_pay.json5
- UseCase-1_14_issue-tickets.json5
- UseCase-1_15_order-overview.json5
```

**Comment by ijpiantanida** [comment]
Hi @roypa, thank you for the suggestion - it's a great idea.
I released v1.8.0 which includes this feature.
