### ISSUE TITLE
Move buffer-shims to dependencies?

### ISSUE THREAD

**Issue by vyorkin** [ijpiantanida/talkback#2]
I guess it should be in dependencies, coz its in the resulting bundle (`dist/index.js`). Am I right or I missed smth?

**Comment by vyorkin** [comment]
The problem is that I'm trying to use it with jest and got this error:
```
  ● Test suite failed to run

    Cannot find module 'buffer-shims' from 'index.js'

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (../../node_modules/talkback/index.js:47:18)
```

**Comment by ijpiantanida** [comment]
You're right!
I just released a fix. Try it.

**Comment by vyorkin** [comment]
in the package.json:
```
"main": "index.js",
```
I think it should be `dist/index.js`, otherwise it is impossible to use it

**Comment by ijpiantanida** [comment]
I'm sorry, I was trying a new deployment script and ended up messing it up.
Should be good to go now.

**Comment by vyorkin** [comment]
thank you! I'll try to provide more feedback later
