### ISSUE TITLE
Can't use host headers?

### ISSUE THREAD

**Issue by floydjd** [ijpiantanida/talkback#27]
Why do you delete host from headers? Can you make this optional?

**Comment by ijpiantanida** [comment]
Keeping the `host` header would make tapes specific to where talkback is running (port & host), which is not very useful.

What do you need the host header for?

**Comment by Floydjd** [comment]
The system I am working with extracts some information from the host header.

**Comment by ijpiantanida** [comment]
The `host` removal only affects tape matching.

The request that will be made to the downstream service will contain its own `host` header (set to the `host` property with which you started talkback).

**Comment by Floydjd** [comment]
Right, but I can only set one host property when I start talkback and my requests use different host headers depending on the request.

**Comment by ijpiantanida** [comment]
Talkback only fronts one service at a time, since it wouldn't have information to know where to route a request in case of multiple hosts.

If you're making requests to multiple services and you want to front them with talkback, you should start one talkback instance per service.

Something like this:
```javascript
const service1 = talback({
  ...baseOpts,
  host: "https://my-service1.com",
  port: 8081,
  path: baseOpts.path + "/service1"
})
service1.start()

const service2 = talback({
  ...baseOpts,
  host: "https://my-service2.com",
  port: 8082,
  path: baseOpts.path + "/service2"
})
service2.start()
```

**Comment by brandonc** [comment]
@ijpiantanida I believe @Floydjd is referring to https://github.com/ijpiantanida/talkback/blob/master/src/request-handler.ts#L125 where the host header is deleted during makeRealRequest

I'm debugging an issue whereby removing the host header causes a mismatch for signed requests (aws in this case) which includes the host header value in it's signing. I also looked into node-fetch, your upstream dependency, and found that it does not add a host header. However, according to Mozilla

> A Host header must be sent in all HTTP/1.1 requests and serves may respond with 400 for any request that lacks a host header

([source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host))

I think the right thing to do is maybe to overwrite the host header if it is not set to be the `options.host`: https://github.com/ijpiantanida/talkback/pull/51

I can't think of a reason that we wouldn't want a host header in this request under any circumstances. WDYT?

**Comment by ijpiantanida** [comment]
`node-fetch` should be adding the host header.

I locally aliased mystrangedomain.com to localhost.
![image](https://user-images.githubusercontent.com/1858238/113363648-3d273a80-9306-11eb-84cc-f51ab11de39b.png)

What `host` option are you giving to talkback?

**Comment by brandonc** [comment]
@ijpiantanida Thanks for looking into this so quickly. You are right! I tested from the fetch side but didn't consider that node `http` is actually setting the host. Once I checked from the server side as you did I saw the host there.

Theoretically, deleting the host header should work! I'm not sure why it does not but I will debug some more.

**Comment by brandonc** [comment]
@ijpiantanida I must have made a mistake with a local modified version of talkback. deleting the host header works fine :grimacing: thank you, again.
