### ISSUE TITLE
console messages

### ISSUE THREAD

**Issue by evert0n** [ijpiantanida/talkback#3]
Hi nice work with this module.

The console messages like https://github.com/ijpiantanida/talkback/blob/master/src/tape-store.js#L42 don't play well with some test reporters I would like to have the option to disable those, could it be a configurable flag (`verbose`/`debug`) like `summary`? Or maybe use the `debug` module?

**Comment by ijpiantanida** [comment]
@evert0n thanks for the suggestion.
I added a `silent` option, as I want the messages to be printed by default.

Check `1.1.4`.

**Comment by evert0n** [comment]
@ijpiantanida Thanks
