### ISSUE TITLE
Key order matters when comparing requests

### ISSUE THREAD

**Issue by Vages** [ijpiantanida/talkback#32]
I've experienced problems with requests not being served when their key order changes. I have a PR coming up which fixes this; just wanted to make the issue to have something to tag it onto.

**Comment by Vages** [comment]
From the test "doesn't match pretty printed tapes with different body", it turns out that this behavior is intentional. I'll just write my own bodyMatcher instead. 😄

**Comment by ijpiantanida** [comment]
I think the test was more of a "let's document what's the current behavior" rather than an intentional decision.

I agree that it's better if key order doesn't matter for JSON requests.

I published `2.0.0` with this problem fixed.
Thank you!

**Comment by Vages** [comment]
Thanks!
