### ISSUE TITLE
Disable header matching or provide a matcher

### ISSUE THREAD

**Issue by chetzof** [ijpiantanida/talkback#66]
I've been using nock for a while and tried to migrate to your library.
Much better, easier, great job!

They only issue we have is that our scraping axios client is randomising headers (user agent, etc) on each request. Thus the requests never get matched. Ignore headers is not an option, because there are over 20 headers that may or may not be randomised. Is it possible to provide header matcher function or disabled header matching all-together. 

FYI https://github.com/nock/nock#enable_reqheaders_recording-option
Nock does not bother matching the recordings by headers by default, because it brings a lot of similar issues....

**Comment by ijpiantanida** [comment]
Hi @chetzof, glad you find Talkback useful!

I think setting `allowHeaders: []` should do what you need.
Let me know if that doesn't work.
