### ISSUE TITLE
When starting multiple servers the logging does not use the server name provided in options

### ISSUE THREAD

**Issue by roypa** [ijpiantanida/talkback#75]
I start multiple Talkback servers in the same Node script, each handling the requests to a specific backend server.

The code looks something like this:
```TypeScript
const startTalkbackServer = (serverName: string) => {
  const options = {
    name: serverName,
    host: config.get<string>(`${serverName}.talkbackUrl`),
    port: config.get<string>(`${serverName}.talkbackPort`),
    path: `./talkback/cached_responses/${serverName}`,
    // ...
  };

  const server = talkback(options);
  server.start(() => {
    console.log(`Talkback server started on http://localhost:${options.port} for ${options.host} with tapes at ${options.path}`);
  });
};

['accounts', 'customers'].forEach(startTalkbackServer);
```

This works very well. The only issue we have with this, is that the log output from each of the servers does not reflect the server name provided in the options. The log output from both servers have the same name in the log line. This is always the name of the last server started.

For example when the the summary is being printed from these two servers, it looks like this:
```
[talkback] 2022-06-23T07:55:49.200Z [customers] [INFO] ===== SUMMARY =====
...
[talkback] 2022-06-23T07:55:49.300Z [customers] [INFO] ===== SUMMARY =====
...
```

Any idea why this is happening?

**Comment by ijpiantanida** [comment]
Great call @scmx, the global logger was definitely a problem.

This should be fixed in v3.0.2
