### ISSUE TITLE
Logo for talkback

### ISSUE THREAD

**Issue by denislutz** [ijpiantanida/talkback#83]
Hi,

Talkback deserves love ;-) .

So I created some logos for free, if you like one feel free to use it. Sorry I am just a software dev not a design guy.

![talk_1](https://user-images.githubusercontent.com/190421/219953714-980004df-6ef4-4923-9e52-529b4ab186e9.png)
![talk_2](https://user-images.githubusercontent.com/190421/219953716-6afb9766-44b9-4dae-9deb-0154dafc012e.png)
![talk_3](https://user-images.githubusercontent.com/190421/219953717-3bfb52d7-4486-4eb5-8d8e-77d82d18b89b.png)
![talk_4](https://user-images.githubusercontent.com/190421/219953719-a547351a-a712-49ac-ab91-f384413be5eb.png)
![talk_5](https://user-images.githubusercontent.com/190421/219953720-c3733e1a-524a-41ee-b570-52745363e6de.png)

**Comment by ijpiantanida** [comment]
Thank you @denislutz! These are amazing and will definitely use one of them. I loved the first one :)
