### ISSUE TITLE
ng-talkback vs talkback

### ISSUE THREAD

**Issue by digeomel** [ijpiantanida/talkback#85]
Hi, what is the difference between the two npm modules?
https://www.npmjs.com/package/talkback
https://www.npmjs.com/package/ng-talkback
Both point to the same repo, here, but ng-talkback has no information on npm.
I was expecting ng-talkback to have some relation to Angular, but I don't see any.
What am I missing?

**Comment by digeomel** [comment]
My bad, totally different repo from a totally different person:
https://github.com/darekf77/ng-talkback
Yet, it is confusing.

**Comment by ijpiantanida** [comment]
Thanks for bringing this up @digeomel.
I've contacted the package author to see if the npm package details can be updated.
