### ISSUE TITLE
feat: add corporate proxy agent

### ISSUE THREAD

**Issue by tristanrobert** [ijpiantanida/talkback#95]
It would need a way to fetch behind corporate proxy when recording requests.

**Comment by ijpiantanida** [comment]
This is now supported in v4.2.0 through the new `httpClient` option ([see README](https://github.com/ijpiantanida/talkback?tab=readme-ov-file#http-client-options)).

Let me know if this doesn't work.

**Comment by tristanrobert** [comment]
It works fine. Thank you. In the doc, there is a mistake it would be:
`httpClient: { fetchOptions: {agent}}`

**Comment by tristanrobert** [comment]
Now I have a 301 redirect (cloudfare), which I fix it adding this:
`httpClient: { fetchOptions: {agent, redirect: 'follow', follow: 1}}`
Then I have a 404 and an empty body. I don't know yet how to fix it.
